(defun pacmanfiles-ediff (button)
  (let* ((file-b (button-label button))
		 (file-a (concat "/sudo::" (replace-regexp-in-string "\\.pac\\(new\\|save\\|orig\\)$" "" file-b))))
	(ediff-files file-a file-b)))


(defun pacmanfiles()
  (interactive)
  (with-current-buffer (get-buffer-create"*pacnew*")
	(delete-region (point-min) (point-max))
	(let ((pac-files (split-string (shell-command-to-string "locate -e --regexp '\\.pac\\(new\\|save\\|orig\\)$'") "\n"))
		  (var))
	  (dolist (var pac-files)
		(insert-button var 'action 'pacmanfiles-ediff)
		(insert "\n")))))
